### ISSUE TITLE
linux agent installation problem

### ISSUE THREAD

**Issue by leuksn** [AtlasInsideCorp/UTMStackAgent#4]
hello the linux-agent installation keeps failing
UTMStack ERROR: can't remove agent dependencies or configurations: exit status 1

**Comment by 347ls** [comment]
Ran into the same problem today. Any solutions so far?

**Comment by osmontero** [comment]
Hi. Thanks for writing. Please ask your questions in https://serverfault.com/ and use UTMSTACK as tag
